version: "3.3"
services:

  nginx:
    image: konstantinzubarev/my-nginx:v1.1
    container_name: nginx
    depends_on: 
      - php-fpm
    volumes:
      - ./file/nginx.conf:/etc/nginx/nginx.conf
      - ./file/index/:/www/
    ports:
      - 80:80
    networks:
      - web

  php-fpm:
    image: konstantinzubarev/my-php:v1.1
    container_name: php-fpm
    volumes:
      - ./file/www.conf:/etc/php7/php-fpm.d/www.conf
      - ./file/index/:/www/
    ports:
      - 9000
    networks:
      - web

networks:
  web: